// mod struct_demo;
// mod tuple_demo;
// mod expressions_demo;
// mod expressions_a;
// mod ownership_demo;
// mod ownership_a;
// mod imp_demo;
// mod imp_a;
// mod vector_demo;
// mod vector_a;
// mod strings_demo;
// mod strings_a;
// mod derive_demo;
// mod type_annotations_demo;
// mod advance_match_demo;
// mod option_demo;
// mod option_a;
// mod documention_demo;
// mod doc_a;
// mod result_demo;
// mod result_a;
mod result_c;
fn main() {
    // struct_demo::struct_main();
    // tuple_demo::tuple_main();
    // expressions_demo::expressions_main();
    // expressions_a::expressions_a();
    // ownership_demo::ownership_demo();
    // ownership_a::ownership_a();
    // imp_demo::imp_demo();
    // imp_a::imp_a();
    // vector_demo::vector_demo();
    // vector_a::vector_a();
    // strings_demo::strings_demo();
    // strings_a::strings_a();
    // derive_demo::derive_demo();
    // type_annotations_demo::type_annotations_demo();
    // advance_match_demo::advance_match_demo();
    // option_demo::option_demo();
    // option_a::option_a();
    // documention_demo::documention_demo();
    // doc_a::doc_a();
    // result_demo::result_demo();
    // result_a::result_a();
    result_c::result_c();
}
